[font]
size = 12

[font.normal]
family = "JetbrainsMono Nerd Font Mono"

[window]
startup_mode = "Fullscreen"
option_as_alt = "Both"

[keyboard]
bindings = [
    { key = "F11", mods = "Control", chars = "\uf601" }, # ğŸ˜
    { key = "F12", mods = "Control", chars = "\u2660" }, # â™ 
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left",  mods = "Alt", chars = "\u001BB" },
    { key = "F10", action = "ToggleFullscreen" }, # ğŸ˜
]
